<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="UTF-8">
    <title>Hardkode</title>
    <meta property="og:title" content="Hardkode" />
    <meta property="og:type" content="article" />
    <meta property="og:image" content="https://github.com/Kommendant/hardkode/blob/gh-pages/images/fbImageShare.png?raw=true" />
    <meta property="og:url" content="www.hardkode.com" />
    <meta property="og:description" content="Hardkode is a project between a group of friends aimed towards taking over the world and overthrowing the overlords of Mars." />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="/static/Css/normalize.css" media="screen">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="/static/Css/stylesheet.css" media="screen">
    <link rel="stylesheet" type="text/css" href="/static/Css/github-light.css" media="screen">
  </head>
  <body>
  
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '780368745405026',
      xfbml      : true,
      version    : 'v2.4'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
 


    <section class="page-header">
      <h1 class="project-name">Hardkode</h1>
      <h2 class="project-tagline"></h2>
      <a href="https://github.com/Kommendant/hardkode" class="btn">View on GitHub</a>
      <a href="brolof/brolofIndex.html" class="btn">Brolof</a> <!-- I am using a relative path instead of an absolute -->
      <a href="/jonas" class="btn">Jonas</a>
      <a href="/simon" class="btn">Essenjiiii</a>
      <a href="/filip" class="btn">Filip</a>
     </section>

    <section class="main-content">

<div class = "fb-like"
  data-href = "http://www.hardkode.com/"
  data-width = "500"
  data-layout = "standard" data-action = "like"
  data-show-faces = "true"
  data-share = "true"> </div>
      <h3>

        <p>
          Having trouble with Pages? Check out our <a href="https://help.github.com/pages">documentation</a> or <a href="https://github.com/contact">contact support</a> and we’ll help you sort it out.
        </p>
        <p>
        Latest commit made by: {{latest_commit_by}}
        </p>
          <footer class="site-footer">
          <span class="site-footer-owner"><a href="https://github.com/Kommendant/hardkode">Hardkode</a> is maintained by The Hardkode crew.</span>

          <span class="site-footer-credits">This page was generated by <a href="https://pages.github.com">GitHub Pages</a> using the <a href="https://github.com/jasonlong/cayman-theme">Cayman theme</a> by <a href="https://twitter.com/jasonlong">Jason Long</a>.</span>
        </footer>
      </h3>
    </section>
  
  </body>
</html>
